name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi there, Thanks a lot for raising your first issue, we'll look into it asap. Also please mention if you wish to work on the issue as well so you could be assigned"
        pr-message: "Hi there, Thanks a lot for your first pull request, we'll be reviewing it asap :)"
